Vagrant.configure("2") do |config|
 
  config.vm.box = "centos/7"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4
  config.vm.provision "shell", path: "provision.sh"
end


  # https://github.com/dotless-de/vagrant-vbguest/issues/311
  # Resolve o problema de atualização do kernel da box centos/7
  # que impede a execução do provision.sh
