# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.provision "shell", path: "provision.sh"# inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
